###
GET   http://localhost:3333/api/lawyer

### 
DELETE  http://localhost:3333/api/lawyer/1deefdf1-1c22-4e19-8771-9b8d3eb47c65
Content-Type: application/json

{
  "name": "João Castro3",
  "email": "joao@advocacia.com",
  "oabNumber": "OAB123452",
  "specialty": "Direito Civil1",
  "phone": "119999999992"
}

